@contoso_pizza_host_address = http://localhost:5031

GET {{contoso_pizza_host_address}}/weatherforecast/
Accept: application/json

###

GET http://localhost:5031/Pizza
Accept: application/json

###


GET http://localhost:5031/Pizza/5
Accept: application/json

###